export const GOUVERNORATS = [
  "Ariana","Béja","Ben Arous","Bizerte","Gabès","Gafsa",
  "Jendouba","Kairouan","Kasserine","Kébili","Kef","Mahdia",
  "Manouba","Médenine","Monastir","Nabeul","Sfax","Sidi Bouzid",
  "Siliana","Sousse","Tataouine","Tozeur","Tunis","Zaghouan",
];

export const DELEGATIONS = {
  "Ariana":      ["Ariana Ville","Ettadhamen","Kalâat el-Andalous","La Soukra","Mnihla","Raoued","Sidi Thabet"],
  "Béja":        ["Béja Nord","Béja Sud","Amdoun","Goubellat","Medjez el-Bab","Nefza","Téboursouk","Testour","Thibar"],
  "Ben Arous":   ["Ben Arous","Bou Mhel el-Bassatine","El Mourouj","Ezzahra","Fouchana","Hammam Chott","Hammam Lif","Khalidia","Medina Jedida","Mégrine","Mohamedia","Mornag","Radès"],
  "Bizerte":     ["Bizerte Nord","Bizerte Sud","El Alia","Ghezala","Ghar el-Melh","Joumine","Mateur","Menzel Bourguiba","Menzel Jemil","Ras Jebel","Sejnane","Tinja","Utique","Zarzouna"],
  "Gabès":       ["Gabès Médina","Gabès Ouest","Gabès Sud","El Hamma","Ghannouch","Mareth","Matmata","Menzel el-Habib","Nouvelle Matmata","Ouedhref"],
  "Gafsa":       ["Gafsa Nord","Gafsa Sud","Belkhir","El Guettar","El Ksar","Mdhilla","Metlaoui","Moularès","Redeyef","Sened","Sidi Aïch"],
  "Jendouba":    ["Jendouba","Jendouba Nord","Aïn Draham","Balta-Bou Aouane","Bou Salem","Fernana","Ghardimaou","Oued Mliz","Tabarka"],
  "Kairouan":    ["Kairouan Nord","Kairouan Sud","Bouhajla","Chebika","Cherarda","El Alâa","Haffouz","Hajeb El Ayoun","Nasrallah","Oueslatia","Sbikha"],
  "Kasserine":   ["Kasserine Nord","Kasserine Sud","Aïn Jedey","El Ayoun","Ezzouhour","Fériana","Foussana","Haïdra","Hassi El Ferid","Jediliane","Majel Bel Abbès","Sbeitla","Thala"],
  "Kébili":      ["Kébili Nord","Kébili Sud","Douz Nord","Douz Sud","Faouar","Souk Lahad"],
  "Kef":         ["Kef Est","Kef Ouest","Dahmani","El Ksour","Jerissa","Kalâat Senan","Kalâat Khasba","Nebeur","Sakiet Sidi Youssef","Tajerouine"],
  "Mahdia":      ["Mahdia","Bou Merdes","Chebba","Chorbane","El Bradaa","Essouassi","Hebira","Ksour Essef","Melloulèche","Ouled Chamekh","Sidi Alouane"],
  "Manouba":     ["Manouba","Den Den","Douar Hicher","El Battan","Jedaida","Mornaguia","Oued Ellil","Tebourba"],
  "Médenine":    ["Médenine Nord","Médenine Sud","Ben Gardane","Beni Khedache","Djerba Ajim","Djerba Houmt Souk","Djerba Midoun","Sidi Makhlouf","Zarzis"],
  "Monastir":    ["Monastir","Amiret El Fehoul","Bembla","Beni Hassen","Bokri","El Sahline","Jemmal","Ksar Hellal","Ksibet el-Mediouni","Ouerdanine","Sahline","Sayada-Lamta-Bou Hajar","Téboulba","Zéramdine"],
  "Nabeul":      ["Nabeul","Béni Khiar","Bou Argoub","Dar Chaâbane El Fehri","El Haouaria","El Mida","Grombalia","Hammamet","Kelibia","Korba","Menzel Bouzelfa","Menzel Temime","Soliman","Takelsa"],
  "Sfax":        ["Sfax Ville","Sfax Ouest","Agareb","Bir Ali Ben Khalifa","El Amra","El Ghraiba","Djebeniana","Hencha","Kerkenah","Mahres","Menzel Chaker","Sakiet Eddaïer","Sakiet Ezzit","Skhira","Thyna"],
  "Sidi Bouzid": ["Sidi Bouzid Est","Sidi Bouzid Ouest","Ben Aoun","Bir El Hafey","Cebbala Ouled Asker","Jilma","Mazzouna","Meknassy","Menzel Bouzaiane","Ouled Haffouz","Regueb","Sidi Ali Ben Aoun"],
  "Siliana":     ["Siliana Nord","Siliana Sud","Bargou","Bou Arada","El Aroussa","El Krib","Gaâfour","Kesra","Makthar","Rouhia","Sidi Bou Rouis"],
  "Sousse":      ["Sousse Médina","Sousse Riadh","Sousse Jawhara","Sousse Sidi Abdelhamid","Akouda","Bou Ficha","Enfidha","Hammam Sousse","Hergla","Kalâa Kebira","Kalâa Seghira","Kondar","M'saken","Sidi Bou Ali","Sidi El Hani"],
  "Tataouine":   ["Tataouine Nord","Tataouine Sud","Bir Lahmar","Dehiba","Ghomrassen","Remada","Smar"],
  "Tozeur":      ["Tozeur","Degache","El Hamma du Jerid","Hezoua","Nefta","Tameghza"],
  "Tunis":       ["Bab Bhar","Bab Souika","Carthage","Cité El Khadra","El Hrairia","El Kabaria","El Kram","El Menzah","El Omrane","El Omrane Supérieur","El Ouardia","Ettahrir","Ezzouhour","Jebel Jelloud","La Goulette","La Marsa","Le Bardo","Médina","Séjoumi","Sidi El Béchir","Sidi Hassine"],
  "Zaghouan":    ["Zaghouan","Bir Mcherga","El Fahs","En Nadhour","Saouaf","Zriba"],
};

const V = {
  "Bab Bhar":              ["Bab Bhar","Belvédère","Montplaisir"],
  "Bab Souika":            ["Bab Souika","Halfaouine","Bab El Khadra"],
  "Carthage":              ["Carthage Dermech","Carthage Hannibal","Sidi Bou Saïd","Aïn Zaghouan"],
  "La Marsa":              ["La Marsa","Gammarth","Marsa Cube"],
  "La Goulette":           ["La Goulette","Kheireddine"],
  "Le Bardo":              ["Le Bardo","Cité Mahrajène"],
  "El Menzah":             ["El Menzah 1","El Menzah 5","El Menzah 6","El Menzah 9","El Manar"],
  "Médina":                ["Médina de Tunis"],
  "Cité El Khadra":        ["Cité El Khadra","Montplaisir"],
  "El Omrane":             ["El Omrane","Montfleury"],
  "El Ouardia":            ["El Ouardia","Mellassine"],
  "Ariana Ville":          ["Ariana","Centre Urbain Nord","Ghazela Technopole"],
  "Ettadhamen":            ["Ettadhamen","Mnihla"],
  "La Soukra":             ["La Soukra","Aïn Zaghouan Nord","Borj Louzir"],
  "Raoued":                ["Raoued","Kalâat el-Andalous"],
  "Ben Arous":             ["Ben Arous","Chotrana"],
  "El Mourouj":            ["El Mourouj 1","El Mourouj 2","El Mourouj 3","El Mourouj 4","El Mourouj 5","El Mourouj 6"],
  "Ezzahra":               ["Ezzahra"],
  "Hammam Lif":            ["Hammam Lif","Borj Cédria"],
  "Mégrine":               ["Mégrine","Mégrine Coteau"],
  "Radès":                 ["Radès"],
  "Hammam Chott":          ["Hammam Chott"],
  "Fouchana":              ["Fouchana"],
  "Mornag":                ["Mornag"],
  "Manouba":               ["Manouba"],
  "Den Den":               ["Den Den"],
  "Douar Hicher":          ["Douar Hicher"],
  "Jedaida":               ["Jedaïda"],
  "Tebourba":              ["Tebourba"],
  "Sousse Médina":         ["Sousse","Sousse Médina"],
  "Hammam Sousse":         ["Hammam Sousse"],
  "Akouda":                ["Akouda"],
  "M'saken":               ["M'saken"],
  "Kalâa Kebira":          ["Kalâa Kebira"],
  "Enfidha":               ["Enfidha","Kondar"],
  "Monastir":              ["Monastir","Skanes"],
  "Ksar Hellal":           ["Ksar Hellal"],
  "Jemmal":                ["Jemmal"],
  "Zéramdine":             ["Zéramdine"],
  "Nabeul":                ["Nabeul"],
  "Hammamet":              ["Hammamet","Hammamet Nord","Hammamet Sud","Yasmine Hammamet"],
  "Kelibia":               ["Kélibia"],
  "Grombalia":             ["Grombalia"],
  "Soliman":               ["Soliman"],
  "Sfax Ville":            ["Sfax","Sfax Centre"],
  "Sfax Ouest":            ["Sfax Ouest"],
  "Sakiet Eddaïer":        ["Sakiet Eddaïer"],
  "Sakiet Ezzit":          ["Sakiet Ezzit"],
  "Bizerte Nord":          ["Bizerte"],
  "Bizerte Sud":           ["Bizerte Sud"],
  "Menzel Bourguiba":      ["Menzel Bourguiba"],
  "Mateur":                ["Mateur"],
  "Ras Jebel":             ["Ras Jebel"],
  "Gabès Médina":          ["Gabès"],
  "Gabès Ouest":           ["Gabès Ouest"],
  "Gabès Sud":             ["Gabès Sud"],
  "El Hamma":              ["El Hamma"],
  "Ghannouch":             ["Ghannouch"],
  "Kairouan Nord":         ["Kairouan"],
  "Kairouan Sud":          ["Kairouan Sud"],
  "Sbikha":                ["Sbikha"],
  "Haffouz":               ["Haffouz"],
  "Gafsa Nord":            ["Gafsa"],
  "Gafsa Sud":             ["Gafsa Sud"],
  "Metlaoui":              ["Metlaoui"],
  "Redeyef":               ["Redeyef"],
  "Moularès":              ["Moularès"],
  "Médenine Nord":         ["Médenine"],
  "Médenine Sud":          ["Médenine Sud"],
  "Zarzis":                ["Zarzis","Zarzis Plage"],
  "Ben Gardane":           ["Ben Gardane"],
  "Djerba Houmt Souk":     ["Houmt Souk"],
  "Djerba Midoun":         ["Midoun","Aghir"],
  "Djerba Ajim":           ["Ajim"],
  "Kasserine Nord":        ["Kasserine"],
  "Kasserine Sud":         ["Kasserine Sud"],
  "Sbeitla":               ["Sbeitla"],
  "Thala":                 ["Thala"],
  "Fériana":               ["Fériana"],
  "Béja Nord":             ["Béja"],
  "Medjez el-Bab":         ["Medjez el-Bab"],
  "Testour":               ["Testour"],
  "Zaghouan":              ["Zaghouan"],
  "El Fahs":               ["El Fahs"],
  "Siliana Nord":          ["Siliana"],
  "Makthar":               ["Makthar"],
  "Gaâfour":               ["Gaâfour"],
  "Sidi Bouzid Est":       ["Sidi Bouzid"],
  "Sidi Bouzid Ouest":     ["Sidi Bouzid Ouest"],
  "Regueb":                ["Regueb"],
  "Meknassy":              ["Meknassy"],
  "Kébili Nord":           ["Kébili"],
  "Douz Nord":             ["Douz"],
  "Tozeur":                ["Tozeur"],
  "Nefta":                 ["Nefta"],
  "Degache":               ["Degache"],
  "Tataouine Nord":        ["Tataouine"],
  "Ghomrassen":            ["Ghomrassen"],
  "Dehiba":                ["Dehiba"],
  "Mahdia":                ["Mahdia"],
  "Chebba":                ["Chebba"],
  "Ksour Essef":           ["Ksour Essef"],
  "Kef Est":               ["Le Kef"],
  "Kef Ouest":             ["Le Kef Ouest"],
  "Dahmani":               ["Dahmani"],
  "Tajerouine":            ["Tajerouine"],
  "Jendouba":              ["Jendouba"],
  "Tabarka":               ["Tabarka"],
  "Aïn Draham":            ["Aïn Draham"],
  "Bou Salem":             ["Bou Salem"],
  "Ghardimaou":            ["Ghardimaou"],
};

export const getVilles = (delegation) => V[delegation] || [delegation];
